/**
 * liasseModelReference.ts
 * Source de vérité unique — structure du modèle Excel officiel SYSCOHADA
 * Fichier: Liasse_systeme_normal_2024_V9_AJM.xlsx (84 onglets)
 *
 * IMPORTANT: Ce fichier est généré à partir de l'analyse du modèle Excel.
 * Ne pas modifier manuellement — relancer l'extraction si le modèle change.
 */

// ── Types ──

export interface RefLigne {
  ref: string
  libelle: string
  isTotal?: boolean    // Ligne de total (formule SUM dans Excel)
  isSousTotal?: boolean // Sous-total intermédiaire
  isSection?: boolean  // En-tête de section (bold, pas de valeur)
}

export interface CellTarget {
  /** Onglet cible dans le modèle Excel */
  sheet: string
  /** REF de la ligne */
  ref: string
  /** Champ: brut, amort, netN, netN1, valN, valN1 */
  field: string
  /** Adresse cellule Excel (ex: F12) */
  cell: string
  /** true si la cellule contient une formule Excel — NE PAS ÉCRASER */
  hasFormula: boolean
}

// ══════════════════════════════════════════════════════════════
// STRUCTURE DES 4 ÉTATS FINANCIERS — REFs et libellés exacts
// ══════════════════════════════════════════════════════════════

export const ACTIF_REFS: RefLigne[] = [
  { ref: 'AD', libelle: 'IMMOBILISATIONS INCORPORELLES', isSousTotal: true },
  { ref: 'AE', libelle: 'Frais de développement et de prospection' },
  { ref: 'AF', libelle: 'Brevets, licences, logiciels, et droits similaires' },
  { ref: 'AG', libelle: 'Fonds commercial et droit au bail' },
  { ref: 'AH', libelle: 'Autres immobilisations incorporelles' },
  { ref: 'AI', libelle: 'IMMOBILISATIONS CORPORELLES', isSousTotal: true },
  { ref: 'AJ', libelle: 'Terrains' },
  { ref: 'AK', libelle: 'Bâtiments' },
  { ref: 'AL', libelle: 'Aménagements, agencements et installations' },
  { ref: 'AM', libelle: 'Matériel, mobilier et actifs biologiques' },
  { ref: 'AN', libelle: 'Matériel de transport' },
  { ref: 'AP', libelle: 'AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS', isSousTotal: true },
  { ref: 'AQ', libelle: 'IMMOBILISATIONS FINANCIERES', isSousTotal: true },
  { ref: 'AR', libelle: 'Titres de participation' },
  { ref: 'AS', libelle: 'Autres immobilisations financières' },
  { ref: 'AZ', libelle: 'TOTAL ACTIF IMMOBILISE', isTotal: true },
  { ref: 'BA', libelle: 'ACTIF CIRCULANT HAO' },
  { ref: 'BB', libelle: 'STOCKS ET ENCOURS' },
  { ref: 'BG', libelle: 'CREANCES ET EMPLOIS ASSIMILES', isSousTotal: true },
  { ref: 'BH', libelle: 'Fournisseurs avances versées' },
  { ref: 'BI', libelle: 'Clients' },
  { ref: 'BJ', libelle: 'Autres créances' },
  { ref: 'BK', libelle: 'TOTAL ACTIF CIRCULANT', isTotal: true },
  { ref: 'BQ', libelle: 'Titres de placement' },
  { ref: 'BR', libelle: 'Valeurs à encaisser' },
  { ref: 'BS', libelle: 'Banques, chèques postaux, caisse et assimilés' },
  { ref: 'BT', libelle: 'TOTAL TRESORERIE-ACTIF', isTotal: true },
  { ref: 'BU', libelle: 'Ecart de conversion-Actif' },
  { ref: 'BZ', libelle: 'TOTAL GENERAL', isTotal: true },
]

export const PASSIF_REFS: RefLigne[] = [
  { ref: 'CA', libelle: 'Capital' },
  { ref: 'CB', libelle: 'Apporteurs capital non appelé (-)' },
  { ref: 'CD', libelle: 'Primes liées au capital social' },
  { ref: 'CE', libelle: 'Ecarts de réévaluation' },
  { ref: 'CF', libelle: 'Réserves indisponibles' },
  { ref: 'CG', libelle: 'Réserves libres' },
  { ref: 'CH', libelle: 'Report à nouveau (+ ou -)' },
  { ref: 'CJ', libelle: "Résultat net de l'exercice (bénéfice + ou perte -)" },
  { ref: 'CL', libelle: "Subventions d'investissement" },
  { ref: 'CM', libelle: 'Provisions réglementées' },
  { ref: 'CP', libelle: 'TOTAL CAPITAUX PROPRES ET RESSOURCES ASSIMILEES', isTotal: true },
  { ref: 'DA', libelle: 'Emprunts et dettes financières diverses' },
  { ref: 'DB', libelle: 'Dettes de location-acquisition' },
  { ref: 'DC', libelle: 'Provisions pour risques et charges' },
  { ref: 'DD', libelle: 'TOTAL DETTES FINANCIERES ET RESSOURCES ASSIMILEES', isTotal: true },
  { ref: 'DF', libelle: 'TOTAL RESSOURCES STABLES', isTotal: true },
  { ref: 'DH', libelle: 'Dettes circulantes HAO' },
  { ref: 'DI', libelle: 'Clients, avances reçues' },
  { ref: 'DJ', libelle: "Fournisseurs d'exploitation" },
  { ref: 'DK', libelle: 'Dettes fiscales et sociales' },
  { ref: 'DM', libelle: 'Autres dettes' },
  { ref: 'DN', libelle: 'Provisions pour risques et charges à court terme' },
  { ref: 'DP', libelle: 'TOTAL PASSIF CIRCULANT', isTotal: true },
  { ref: 'DQ', libelle: "Banques, crédits d'escompte" },
  { ref: 'DR', libelle: 'Banques, établissements financiers et crédits de trésorerie' },
  { ref: 'DT', libelle: 'TOTAL TRESORERIE-PASSIF', isTotal: true },
  { ref: 'DV', libelle: 'Ecart de conversion-Passif' },
  { ref: 'DZ', libelle: 'TOTAL GENERAL', isTotal: true },
]

export const RESULTAT_REFS: RefLigne[] = [
  { ref: 'TA', libelle: 'Ventes de marchandises' },
  { ref: 'RA', libelle: 'Achats de marchandises' },
  { ref: 'RB', libelle: 'Variation de stocks de marchandises' },
  { ref: 'XA', libelle: 'MARGE COMMERCIALE (Somme TA à RB)', isTotal: true },
  { ref: 'TB', libelle: 'Ventes de produits fabriqués' },
  { ref: 'TC', libelle: 'Travaux, services vendus' },
  { ref: 'TD', libelle: 'Produits accessoires' },
  { ref: 'XB', libelle: "CHIFFRE D'AFFAIRES (A + B + C + D)", isTotal: true },
  { ref: 'TE', libelle: 'Production stockée (ou déstockage)' },
  { ref: 'TF', libelle: 'Production immobilisée' },
  { ref: 'TG', libelle: "Subventions d'exploitation" },
  { ref: 'TH', libelle: 'Autres produits' },
  { ref: 'TI', libelle: "Transferts de charges d'exploitation" },
  { ref: 'RC', libelle: 'Achats de matières premières et fournitures liées' },
  { ref: 'RD', libelle: 'Variation de stocks de matières premières et fournitures liées' },
  { ref: 'RE', libelle: 'Autres achats' },
  { ref: 'RF', libelle: "Variation de stocks d'autres approvisionnements" },
  { ref: 'RG', libelle: 'Transports' },
  { ref: 'RH', libelle: 'Services extérieurs' },
  { ref: 'RI', libelle: 'Impôts et taxes' },
  { ref: 'RJ', libelle: 'Autres charges' },
  { ref: 'XC', libelle: 'VALEUR AJOUTEE (XB +RA+RB) + (somme TE à RJ)', isTotal: true },
  { ref: 'RK', libelle: 'Charges de personnel' },
  { ref: 'XD', libelle: "EXCEDENT BRUT D'EXPLOITATION (XC+RK)", isTotal: true },
  { ref: 'TJ', libelle: "Reprises d'amortissements, provisions et dépréciations" },
  { ref: 'RL', libelle: 'Dotations aux amortissements, aux provisions et dépréciations' },
  { ref: 'XE', libelle: "RESULTAT D'EXPLOITATION (XD+TJ+ RL)", isTotal: true },
  { ref: 'TK', libelle: 'Revenus financiers et assimilés' },
  { ref: 'TL', libelle: 'Reprises de provisions et dépréciations financières' },
  { ref: 'TM', libelle: 'Transferts de charges financières' },
  { ref: 'RM', libelle: 'Frais financiers et charges assimilées' },
  { ref: 'RN', libelle: 'Dotations aux provisions et aux dépréciations financières' },
  { ref: 'XF', libelle: 'RESULTAT FINANCIER (somme TK à RN)', isTotal: true },
  { ref: 'XG', libelle: 'RESULTAT DES ACTIVITES ORDINAIRES (XE+XF)', isTotal: true },
  { ref: 'TN', libelle: "Produits des cessions d'immobilisations" },
  { ref: 'TO', libelle: 'Autres Produits HAO' },
  { ref: 'RO', libelle: "Valeurs comptables des cessions d'immobilisations" },
  { ref: 'RP', libelle: 'Autres Charges HAO' },
  { ref: 'XH', libelle: 'RESULTAT HORS ACTIVITES ORDINAIRES (somme TN à RP)', isTotal: true },
  { ref: 'RQ', libelle: 'Participation des travailleurs' },
  { ref: 'RS', libelle: 'Impôts sur le résultat' },
  { ref: 'XI', libelle: 'RESULTAT NET (XG+XH+RQ+RS)', isTotal: true },
]

export const TFT_REFS: RefLigne[] = [
  { ref: 'ZA', libelle: 'Trésorerie nette au 1er janvier' },
  { ref: 'FA', libelle: "Capacité d'Autofinancement Globale (CAFG)" },
  { ref: 'FB', libelle: "- Variation d'actif circulant HAO" },
  { ref: 'FC', libelle: '- Variation des stocks' },
  { ref: 'FD', libelle: '- Variation des créances' },
  { ref: 'FE', libelle: '+ Variation du passif circulant' },
  { ref: 'ZB', libelle: 'Flux de trésorerie provenant des activités opérationnelles (Somme FA à FE)', isTotal: true },
  { ref: 'FF', libelle: "- Décaissements liés aux acquisitions d'immobilisations incorporelles" },
  { ref: 'FG', libelle: "- Décaissements liés aux acquisitions d'immobilisations corporelles" },
  { ref: 'FH', libelle: "- Décaissements liés aux acquisitions d'immobilisations financières" },
  { ref: 'FI', libelle: "+ Encaissements liés aux cessions d'immobilisations incorporelles et corporelles" },
  { ref: 'FJ', libelle: "+ Encaissements liés aux cessions d'immobilisations financières" },
  { ref: 'ZC', libelle: "Flux de trésorerie provenant des activités d'investissement (somme FF à FJ)", isTotal: true },
  { ref: 'FK', libelle: '+ Augmentations de capital par apports nouveaux' },
  { ref: 'FL', libelle: "+ Subventions d'investissement reçues" },
  { ref: 'FM', libelle: '- Prélèvements sur le capital' },
  { ref: 'FN', libelle: '- Dividendes versés' },
  { ref: 'ZD', libelle: 'Flux de trésorerie provenant des capitaux propres (somme FK à FN)', isTotal: true },
  { ref: 'FO', libelle: '+ Emprunts' },
  { ref: 'FP', libelle: '+ Autres dettes financières diverses' },
  { ref: 'FQ', libelle: "- Remboursements des emprunts et autres dettes financières" },
  { ref: 'ZE', libelle: 'Flux de trésorerie provenant des capitaux étrangers (somme FO à FQ)', isTotal: true },
  { ref: 'ZF', libelle: 'Flux de trésorerie provenant des activités de financement (D+E)', isTotal: true },
  { ref: 'ZG', libelle: 'VARIATION DE LA TRÉSORERIE NETTE DE LA PÉRIODE (B+C+F)', isTotal: true },
  { ref: 'ZH', libelle: 'Trésorerie nette au 31 Décembre (G+A)', isTotal: true },
]

// ══════════════════════════════════════════════════════════════
// CELL MAP — Coordonnées exactes pour injection Mode B
// Onglet BILAN = source principale (ACTIF cols F-I, PASSIF cols M-N)
// Onglet RESULTAT = cols I-J
// Onglet TFT = cols I-J
// ══════════════════════════════════════════════════════════════

export const CELL_MAP: CellTarget[] = [
  // ── BILAN ACTIF — Onglet BILAN, colonnes F(brut), G(amort), H(netN=formule), I(netN1) ──
  // Lignes de détail (SANS formule — à injecter)
  { sheet: 'BILAN', ref: 'AE', field: 'brut',  cell: 'F12', hasFormula: false },
  { sheet: 'BILAN', ref: 'AE', field: 'amort', cell: 'G12', hasFormula: false },
  { sheet: 'BILAN', ref: 'AE', field: 'netN1', cell: 'I12', hasFormula: false },
  { sheet: 'BILAN', ref: 'AF', field: 'brut',  cell: 'F13', hasFormula: false },
  { sheet: 'BILAN', ref: 'AF', field: 'amort', cell: 'G13', hasFormula: false },
  { sheet: 'BILAN', ref: 'AF', field: 'netN1', cell: 'I13', hasFormula: false },
  { sheet: 'BILAN', ref: 'AG', field: 'brut',  cell: 'F14', hasFormula: false },
  { sheet: 'BILAN', ref: 'AG', field: 'amort', cell: 'G14', hasFormula: false },
  { sheet: 'BILAN', ref: 'AG', field: 'netN1', cell: 'I14', hasFormula: false },
  { sheet: 'BILAN', ref: 'AH', field: 'brut',  cell: 'F15', hasFormula: false },
  { sheet: 'BILAN', ref: 'AH', field: 'amort', cell: 'G15', hasFormula: false },
  { sheet: 'BILAN', ref: 'AH', field: 'netN1', cell: 'I15', hasFormula: false },
  { sheet: 'BILAN', ref: 'AJ', field: 'brut',  cell: 'F17', hasFormula: false },
  { sheet: 'BILAN', ref: 'AJ', field: 'amort', cell: 'G17', hasFormula: false },
  { sheet: 'BILAN', ref: 'AJ', field: 'netN1', cell: 'I17', hasFormula: false },
  { sheet: 'BILAN', ref: 'AK', field: 'brut',  cell: 'F18', hasFormula: false },
  { sheet: 'BILAN', ref: 'AK', field: 'amort', cell: 'G18', hasFormula: false },
  { sheet: 'BILAN', ref: 'AK', field: 'netN1', cell: 'I18', hasFormula: false },
  { sheet: 'BILAN', ref: 'AL', field: 'brut',  cell: 'F19', hasFormula: false },
  { sheet: 'BILAN', ref: 'AL', field: 'amort', cell: 'G19', hasFormula: false },
  { sheet: 'BILAN', ref: 'AL', field: 'netN1', cell: 'I19', hasFormula: false },
  { sheet: 'BILAN', ref: 'AM', field: 'brut',  cell: 'F20', hasFormula: false },
  { sheet: 'BILAN', ref: 'AM', field: 'amort', cell: 'G20', hasFormula: false },
  { sheet: 'BILAN', ref: 'AM', field: 'netN1', cell: 'I20', hasFormula: false },
  { sheet: 'BILAN', ref: 'AN', field: 'brut',  cell: 'F21', hasFormula: false },
  { sheet: 'BILAN', ref: 'AN', field: 'amort', cell: 'G21', hasFormula: false },
  { sheet: 'BILAN', ref: 'AN', field: 'netN1', cell: 'I21', hasFormula: false },
  { sheet: 'BILAN', ref: 'AP', field: 'brut',  cell: 'F22', hasFormula: false },
  { sheet: 'BILAN', ref: 'AP', field: 'amort', cell: 'G22', hasFormula: false },
  { sheet: 'BILAN', ref: 'AP', field: 'netN1', cell: 'I22', hasFormula: false },
  { sheet: 'BILAN', ref: 'AR', field: 'brut',  cell: 'F24', hasFormula: false },
  { sheet: 'BILAN', ref: 'AR', field: 'amort', cell: 'G24', hasFormula: false },
  { sheet: 'BILAN', ref: 'AR', field: 'netN1', cell: 'I24', hasFormula: false },
  { sheet: 'BILAN', ref: 'AS', field: 'brut',  cell: 'F25', hasFormula: false },
  { sheet: 'BILAN', ref: 'AS', field: 'amort', cell: 'G25', hasFormula: false },
  { sheet: 'BILAN', ref: 'AS', field: 'netN1', cell: 'I25', hasFormula: false },
  { sheet: 'BILAN', ref: 'BA', field: 'brut',  cell: 'F27', hasFormula: false },
  { sheet: 'BILAN', ref: 'BA', field: 'amort', cell: 'G27', hasFormula: false },
  { sheet: 'BILAN', ref: 'BA', field: 'netN1', cell: 'I27', hasFormula: false },
  { sheet: 'BILAN', ref: 'BB', field: 'brut',  cell: 'F28', hasFormula: false },
  { sheet: 'BILAN', ref: 'BB', field: 'amort', cell: 'G28', hasFormula: false },
  { sheet: 'BILAN', ref: 'BB', field: 'netN1', cell: 'I28', hasFormula: false },
  { sheet: 'BILAN', ref: 'BH', field: 'brut',  cell: 'F30', hasFormula: false },
  { sheet: 'BILAN', ref: 'BH', field: 'amort', cell: 'G30', hasFormula: false },
  { sheet: 'BILAN', ref: 'BH', field: 'netN1', cell: 'I30', hasFormula: false },
  { sheet: 'BILAN', ref: 'BI', field: 'brut',  cell: 'F31', hasFormula: false },
  { sheet: 'BILAN', ref: 'BI', field: 'amort', cell: 'G31', hasFormula: false },
  { sheet: 'BILAN', ref: 'BI', field: 'netN1', cell: 'I31', hasFormula: false },
  { sheet: 'BILAN', ref: 'BJ', field: 'brut',  cell: 'F32', hasFormula: false },
  { sheet: 'BILAN', ref: 'BJ', field: 'amort', cell: 'G32', hasFormula: false },
  { sheet: 'BILAN', ref: 'BJ', field: 'netN1', cell: 'I32', hasFormula: false },
  { sheet: 'BILAN', ref: 'BQ', field: 'brut',  cell: 'F34', hasFormula: false },
  { sheet: 'BILAN', ref: 'BQ', field: 'amort', cell: 'G34', hasFormula: false },
  { sheet: 'BILAN', ref: 'BQ', field: 'netN1', cell: 'I34', hasFormula: false },
  { sheet: 'BILAN', ref: 'BR', field: 'brut',  cell: 'F35', hasFormula: false },
  { sheet: 'BILAN', ref: 'BR', field: 'amort', cell: 'G35', hasFormula: false },
  { sheet: 'BILAN', ref: 'BR', field: 'netN1', cell: 'I35', hasFormula: false },
  { sheet: 'BILAN', ref: 'BS', field: 'brut',  cell: 'F36', hasFormula: false },
  { sheet: 'BILAN', ref: 'BS', field: 'amort', cell: 'G36', hasFormula: false },
  { sheet: 'BILAN', ref: 'BS', field: 'netN1', cell: 'I36', hasFormula: false },
  { sheet: 'BILAN', ref: 'BU', field: 'brut',  cell: 'F38', hasFormula: false },
  { sheet: 'BILAN', ref: 'BU', field: 'amort', cell: 'G38', hasFormula: false },
  { sheet: 'BILAN', ref: 'BU', field: 'netN1', cell: 'I38', hasFormula: false },

  // ── BILAN PASSIF — Onglet BILAN, colonnes M(netN), N(netN1) ──
  { sheet: 'BILAN', ref: 'CA', field: 'netN',  cell: 'M11', hasFormula: false },
  { sheet: 'BILAN', ref: 'CA', field: 'netN1', cell: 'N11', hasFormula: false },
  { sheet: 'BILAN', ref: 'CB', field: 'netN',  cell: 'M12', hasFormula: false },
  { sheet: 'BILAN', ref: 'CB', field: 'netN1', cell: 'N12', hasFormula: false },
  { sheet: 'BILAN', ref: 'CD', field: 'netN',  cell: 'M13', hasFormula: false },
  { sheet: 'BILAN', ref: 'CD', field: 'netN1', cell: 'N13', hasFormula: false },
  { sheet: 'BILAN', ref: 'CE', field: 'netN',  cell: 'M14', hasFormula: false },
  { sheet: 'BILAN', ref: 'CE', field: 'netN1', cell: 'N14', hasFormula: false },
  { sheet: 'BILAN', ref: 'CF', field: 'netN',  cell: 'M15', hasFormula: false },
  { sheet: 'BILAN', ref: 'CF', field: 'netN1', cell: 'N15', hasFormula: false },
  { sheet: 'BILAN', ref: 'CG', field: 'netN',  cell: 'M16', hasFormula: false },
  { sheet: 'BILAN', ref: 'CG', field: 'netN1', cell: 'N16', hasFormula: false },
  { sheet: 'BILAN', ref: 'CH', field: 'netN',  cell: 'M17', hasFormula: false },
  { sheet: 'BILAN', ref: 'CH', field: 'netN1', cell: 'N17', hasFormula: false },
  { sheet: 'BILAN', ref: 'CJ', field: 'netN',  cell: 'M18', hasFormula: false },
  { sheet: 'BILAN', ref: 'CJ', field: 'netN1', cell: 'N18', hasFormula: false },
  { sheet: 'BILAN', ref: 'CL', field: 'netN',  cell: 'M19', hasFormula: false },
  { sheet: 'BILAN', ref: 'CL', field: 'netN1', cell: 'N19', hasFormula: false },
  { sheet: 'BILAN', ref: 'CM', field: 'netN',  cell: 'M20', hasFormula: false },
  { sheet: 'BILAN', ref: 'CM', field: 'netN1', cell: 'N20', hasFormula: false },
  { sheet: 'BILAN', ref: 'DA', field: 'netN',  cell: 'M22', hasFormula: false },
  { sheet: 'BILAN', ref: 'DA', field: 'netN1', cell: 'N22', hasFormula: false },
  { sheet: 'BILAN', ref: 'DB', field: 'netN',  cell: 'M23', hasFormula: false },
  { sheet: 'BILAN', ref: 'DB', field: 'netN1', cell: 'N23', hasFormula: false },
  { sheet: 'BILAN', ref: 'DC', field: 'netN',  cell: 'M24', hasFormula: false },
  { sheet: 'BILAN', ref: 'DC', field: 'netN1', cell: 'N24', hasFormula: false },
  { sheet: 'BILAN', ref: 'DH', field: 'netN',  cell: 'M27', hasFormula: false },
  { sheet: 'BILAN', ref: 'DH', field: 'netN1', cell: 'N27', hasFormula: false },
  { sheet: 'BILAN', ref: 'DI', field: 'netN',  cell: 'M28', hasFormula: false },
  { sheet: 'BILAN', ref: 'DI', field: 'netN1', cell: 'N28', hasFormula: false },
  { sheet: 'BILAN', ref: 'DJ', field: 'netN',  cell: 'M29', hasFormula: false },
  { sheet: 'BILAN', ref: 'DJ', field: 'netN1', cell: 'N29', hasFormula: false },
  { sheet: 'BILAN', ref: 'DK', field: 'netN',  cell: 'M30', hasFormula: false },
  { sheet: 'BILAN', ref: 'DK', field: 'netN1', cell: 'N30', hasFormula: false },
  { sheet: 'BILAN', ref: 'DM', field: 'netN',  cell: 'M31', hasFormula: false },
  { sheet: 'BILAN', ref: 'DM', field: 'netN1', cell: 'N31', hasFormula: false },
  { sheet: 'BILAN', ref: 'DN', field: 'netN',  cell: 'M32', hasFormula: false },
  { sheet: 'BILAN', ref: 'DN', field: 'netN1', cell: 'N32', hasFormula: false },
  { sheet: 'BILAN', ref: 'DQ', field: 'netN',  cell: 'M35', hasFormula: false },
  { sheet: 'BILAN', ref: 'DQ', field: 'netN1', cell: 'N35', hasFormula: false },
  { sheet: 'BILAN', ref: 'DR', field: 'netN',  cell: 'M36', hasFormula: false },
  { sheet: 'BILAN', ref: 'DR', field: 'netN1', cell: 'N36', hasFormula: false },
  { sheet: 'BILAN', ref: 'DV', field: 'netN',  cell: 'M38', hasFormula: false },
  { sheet: 'BILAN', ref: 'DV', field: 'netN1', cell: 'N38', hasFormula: false },

  // ── BILAN — En-tête entreprise ──
  { sheet: 'BILAN', ref: '_denomination', field: 'denomination', cell: 'C3', hasFormula: false },
  { sheet: 'BILAN', ref: '_adresse',      field: 'adresse',      cell: 'C4', hasFormula: false },
  { sheet: 'BILAN', ref: '_ncc',          field: 'ncc',          cell: 'C5', hasFormula: false },
  { sheet: 'BILAN', ref: '_exercice',     field: 'exerciceClos', cell: 'K5', hasFormula: false },
  { sheet: 'BILAN', ref: '_duree',        field: 'dureeMois',    cell: 'N5', hasFormula: false },
  { sheet: 'BILAN', ref: '_ntd',          field: 'ntd',          cell: 'C6', hasFormula: false },
  { sheet: 'BILAN', ref: '_sigle',        field: 'sigle',        cell: 'N4', hasFormula: false },

  // ── RESULTAT — Onglet RESULTAT, colonnes I(netN), J(netN1) ──
  // Only non-formula cells (detail lines)
  { sheet: 'RESULTAT', ref: 'TA', field: 'netN',  cell: 'I11', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TA', field: 'netN1', cell: 'J11', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RA', field: 'netN',  cell: 'I12', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RA', field: 'netN1', cell: 'J12', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RB', field: 'netN',  cell: 'I13', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RB', field: 'netN1', cell: 'J13', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TB', field: 'netN',  cell: 'I15', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TB', field: 'netN1', cell: 'J15', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TC', field: 'netN',  cell: 'I16', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TC', field: 'netN1', cell: 'J16', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TD', field: 'netN',  cell: 'I17', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TD', field: 'netN1', cell: 'J17', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TE', field: 'netN',  cell: 'I19', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TE', field: 'netN1', cell: 'J19', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TF', field: 'netN',  cell: 'I20', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TF', field: 'netN1', cell: 'J20', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TG', field: 'netN',  cell: 'I21', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TG', field: 'netN1', cell: 'J21', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TH', field: 'netN',  cell: 'I22', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TH', field: 'netN1', cell: 'J22', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TI', field: 'netN',  cell: 'I23', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TI', field: 'netN1', cell: 'J23', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RC', field: 'netN',  cell: 'I24', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RC', field: 'netN1', cell: 'J24', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RD', field: 'netN',  cell: 'I25', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RD', field: 'netN1', cell: 'J25', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RE', field: 'netN',  cell: 'I26', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RE', field: 'netN1', cell: 'J26', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RF', field: 'netN',  cell: 'I27', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RF', field: 'netN1', cell: 'J27', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RG', field: 'netN',  cell: 'I28', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RG', field: 'netN1', cell: 'J28', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RH', field: 'netN',  cell: 'I29', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RH', field: 'netN1', cell: 'J29', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RI', field: 'netN',  cell: 'I30', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RI', field: 'netN1', cell: 'J30', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RJ', field: 'netN',  cell: 'I31', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RJ', field: 'netN1', cell: 'J31', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RK', field: 'netN',  cell: 'I33', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RK', field: 'netN1', cell: 'J33', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TJ', field: 'netN',  cell: 'I35', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TJ', field: 'netN1', cell: 'J35', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RL', field: 'netN',  cell: 'I36', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RL', field: 'netN1', cell: 'J36', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TK', field: 'netN',  cell: 'I38', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TK', field: 'netN1', cell: 'J38', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TL', field: 'netN',  cell: 'I39', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TL', field: 'netN1', cell: 'J39', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TM', field: 'netN',  cell: 'I40', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TM', field: 'netN1', cell: 'J40', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RM', field: 'netN',  cell: 'I41', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RM', field: 'netN1', cell: 'J41', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RN', field: 'netN',  cell: 'I42', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RN', field: 'netN1', cell: 'J42', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TN', field: 'netN',  cell: 'I45', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TN', field: 'netN1', cell: 'J45', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TO', field: 'netN',  cell: 'I46', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'TO', field: 'netN1', cell: 'J46', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RO', field: 'netN',  cell: 'I47', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RO', field: 'netN1', cell: 'J47', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RP', field: 'netN',  cell: 'I48', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RP', field: 'netN1', cell: 'J48', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RQ', field: 'netN',  cell: 'I50', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RQ', field: 'netN1', cell: 'J50', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RS', field: 'netN',  cell: 'I51', hasFormula: false },
  { sheet: 'RESULTAT', ref: 'RS', field: 'netN1', cell: 'J51', hasFormula: false },

  // ── TFT — Onglet TFT, colonnes I(valN), J(valN1) ──
  { sheet: 'TFT', ref: 'ZA', field: 'valN',  cell: 'I10', hasFormula: false },
  { sheet: 'TFT', ref: 'ZA', field: 'valN1', cell: 'J10', hasFormula: false },
  { sheet: 'TFT', ref: 'FA', field: 'valN',  cell: 'I12', hasFormula: false },
  { sheet: 'TFT', ref: 'FA', field: 'valN1', cell: 'J12', hasFormula: false },
  { sheet: 'TFT', ref: 'FB', field: 'valN',  cell: 'I13', hasFormula: false },
  { sheet: 'TFT', ref: 'FB', field: 'valN1', cell: 'J13', hasFormula: false },
  { sheet: 'TFT', ref: 'FC', field: 'valN',  cell: 'I14', hasFormula: false },
  { sheet: 'TFT', ref: 'FC', field: 'valN1', cell: 'J14', hasFormula: false },
  { sheet: 'TFT', ref: 'FD', field: 'valN',  cell: 'I15', hasFormula: false },
  { sheet: 'TFT', ref: 'FD', field: 'valN1', cell: 'J15', hasFormula: false },
  { sheet: 'TFT', ref: 'FE', field: 'valN',  cell: 'I16', hasFormula: false },
  { sheet: 'TFT', ref: 'FE', field: 'valN1', cell: 'J16', hasFormula: false },
  { sheet: 'TFT', ref: 'FF', field: 'valN',  cell: 'I21', hasFormula: false },
  { sheet: 'TFT', ref: 'FF', field: 'valN1', cell: 'J21', hasFormula: false },
  { sheet: 'TFT', ref: 'FG', field: 'valN',  cell: 'I22', hasFormula: false },
  { sheet: 'TFT', ref: 'FG', field: 'valN1', cell: 'J22', hasFormula: false },
  { sheet: 'TFT', ref: 'FH', field: 'valN',  cell: 'I23', hasFormula: false },
  { sheet: 'TFT', ref: 'FH', field: 'valN1', cell: 'J23', hasFormula: false },
  { sheet: 'TFT', ref: 'FI', field: 'valN',  cell: 'I24', hasFormula: false },
  { sheet: 'TFT', ref: 'FI', field: 'valN1', cell: 'J24', hasFormula: false },
  { sheet: 'TFT', ref: 'FJ', field: 'valN',  cell: 'I25', hasFormula: false },
  { sheet: 'TFT', ref: 'FJ', field: 'valN1', cell: 'J25', hasFormula: false },
  { sheet: 'TFT', ref: 'FK', field: 'valN',  cell: 'I28', hasFormula: false },
  { sheet: 'TFT', ref: 'FK', field: 'valN1', cell: 'J28', hasFormula: false },
  { sheet: 'TFT', ref: 'FL', field: 'valN',  cell: 'I29', hasFormula: false },
  { sheet: 'TFT', ref: 'FL', field: 'valN1', cell: 'J29', hasFormula: false },
  { sheet: 'TFT', ref: 'FM', field: 'valN',  cell: 'I30', hasFormula: false },
  { sheet: 'TFT', ref: 'FM', field: 'valN1', cell: 'J30', hasFormula: false },
  { sheet: 'TFT', ref: 'FN', field: 'valN',  cell: 'I31', hasFormula: false },
  { sheet: 'TFT', ref: 'FN', field: 'valN1', cell: 'J31', hasFormula: false },
  { sheet: 'TFT', ref: 'FO', field: 'valN',  cell: 'I34', hasFormula: false },
  { sheet: 'TFT', ref: 'FO', field: 'valN1', cell: 'J34', hasFormula: false },
  { sheet: 'TFT', ref: 'FP', field: 'valN',  cell: 'I35', hasFormula: false },
  { sheet: 'TFT', ref: 'FP', field: 'valN1', cell: 'J35', hasFormula: false },
  { sheet: 'TFT', ref: 'FQ', field: 'valN',  cell: 'I36', hasFormula: false },
  { sheet: 'TFT', ref: 'FQ', field: 'valN1', cell: 'J36', hasFormula: false },
]

// ══════════════════════════════════════════════════════════════
// FORMULES DE CONTRÔLE — Équilibres et cohérences croisées
// ══════════════════════════════════════════════════════════════

export interface ControleRule {
  id: string
  label: string
  severity: 'bloquant' | 'avertissement'
  /** Function receives a map of ref→value and returns the écart (0 = OK) */
  check: (vals: Record<string, number>) => number
}

export const CONTROLES: ControleRule[] = [
  // Bilan Actif
  { id: 'AZ', label: 'Total Actif Immobilisé = AD+AI+AP+AQ', severity: 'bloquant',
    check: v => (v.AD||0) + (v.AI||0) + (v.AP||0) + (v.AQ||0) - (v.AZ||0) },
  { id: 'BK', label: 'Total Actif Circulant = BA+BB+BG', severity: 'bloquant',
    check: v => (v.BA||0) + (v.BB||0) + (v.BG||0) - (v.BK||0) },
  { id: 'BT', label: 'Total Trésorerie-Actif = BQ+BR+BS', severity: 'bloquant',
    check: v => (v.BQ||0) + (v.BR||0) + (v.BS||0) - (v.BT||0) },
  { id: 'BZ', label: 'Total Général Actif = AZ+BK+BT+BU', severity: 'bloquant',
    check: v => (v.AZ||0) + (v.BK||0) + (v.BT||0) + (v.BU||0) - (v.BZ||0) },
  // Bilan Passif
  { id: 'CP', label: 'Total Capitaux Propres = CA-CB+CD+CE+CF+CG+CH+CJ+CL+CM', severity: 'bloquant',
    check: v => (v.CA||0) - (v.CB||0) + (v.CD||0) + (v.CE||0) + (v.CF||0) + (v.CG||0) + (v.CH||0) + (v.CJ||0) + (v.CL||0) + (v.CM||0) - (v.CP||0) },
  { id: 'DD', label: 'Total Dettes Financières = DA+DB+DC', severity: 'bloquant',
    check: v => (v.DA||0) + (v.DB||0) + (v.DC||0) - (v.DD||0) },
  { id: 'DF', label: 'Total Ressources Stables = CP+DD', severity: 'bloquant',
    check: v => (v.CP||0) + (v.DD||0) - (v.DF||0) },
  { id: 'DP', label: 'Total Passif Circulant = DH+DI+DJ+DK+DM+DN', severity: 'bloquant',
    check: v => (v.DH||0) + (v.DI||0) + (v.DJ||0) + (v.DK||0) + (v.DM||0) + (v.DN||0) - (v.DP||0) },
  { id: 'DT', label: 'Total Trésorerie-Passif = DQ+DR', severity: 'bloquant',
    check: v => (v.DQ||0) + (v.DR||0) - (v.DT||0) },
  { id: 'DZ', label: 'Total Général Passif = DF+DP+DT+DV', severity: 'bloquant',
    check: v => (v.DF||0) + (v.DP||0) + (v.DT||0) + (v.DV||0) - (v.DZ||0) },
  // Contrôles croisés
  { id: 'BZ=DZ', label: 'Équilibre Bilan: Total Actif = Total Passif', severity: 'bloquant',
    check: v => (v.BZ||0) - (v.DZ||0) },
  { id: 'CJ=XI', label: 'Résultat Bilan = Résultat CdR', severity: 'bloquant',
    check: v => (v.CJ||0) - (v.XI||0) },
  { id: 'TRESO', label: 'Trésorerie TFT = Trésorerie Bilan (BT-DT)', severity: 'avertissement',
    check: v => (v.BT||0) - (v.DT||0) - (v.ZH||0) },
]

/** Template file path (served from public/) */
export const TEMPLATE_PATH = '/templates/Liasse_systeme_normal_2024_V9_AJM.xlsx'
