#!/bin/bash
# ============================================================
# Liass'Pilot — Production Setup Checklist Script
# ============================================================

echo "============================================"
echo "  Liass'Pilot — Production Setup"
echo "============================================"
echo ""
echo "This script guides you through production setup."
echo ""

echo "--- Step 1: Supabase Configuration ---"
echo "  1. Go to https://supabase.com/dashboard"
echo "  2. Create a new project (or use existing)"
echo "  3. Go to Settings > API"
echo "  4. Copy the URL and anon key"
echo "  5. Set in Vercel environment variables:"
echo "     VITE_SUPABASE_URL=https://YOUR_PROJECT.supabase.co"
echo "     VITE_SUPABASE_ANON_KEY=your-anon-key"
echo ""

echo "--- Step 2: Run Migrations ---"
echo "  supabase link --project-ref YOUR_PROJECT_REF"
echo "  supabase db push"
echo ""

echo "--- Step 3: Stripe Configuration ---"
echo "  1. Go to https://dashboard.stripe.com"
echo "  2. Create 4 prices (Business monthly/yearly, Enterprise monthly/yearly)"
echo "  3. Add lookup_keys: business_monthly, business_yearly, enterprise_monthly, enterprise_yearly"
echo "  4. Set in Vercel:"
echo "     VITE_STRIPE_PUBLISHABLE_KEY=pk_live_..."
echo "     VITE_STRIPE_PRICE_BUSINESS_MONTHLY=price_..."
echo "     VITE_STRIPE_PRICE_BUSINESS_YEARLY=price_..."
echo "     VITE_STRIPE_PRICE_ENTERPRISE_MONTHLY=price_..."
echo "     VITE_STRIPE_PRICE_ENTERPRISE_YEARLY=price_..."
echo "  5. Set in Supabase Edge Functions secrets:"
echo "     STRIPE_SECRET_KEY=sk_live_..."
echo "     STRIPE_WEBHOOK_SECRET=whsec_..."
echo "  6. Create webhook endpoint: https://YOUR_PROJECT.supabase.co/functions/v1/stripe-webhook"
echo "     Events: checkout.session.completed, customer.subscription.updated,"
echo "             customer.subscription.deleted, invoice.payment_failed"
echo ""

echo "--- Step 3b: CinetPay Configuration (Mobile Money) ---"
echo "  1. Go to https://app.cinetpay.com"
echo "  2. Create an account and get API key + Site ID"
echo "  3. Set in Vercel:"
echo "     VITE_CINETPAY_API_KEY=your-api-key"
echo "     VITE_CINETPAY_SITE_ID=your-site-id"
echo "  4. Set in Supabase Edge Functions secrets:"
echo "     CINETPAY_API_KEY=your-api-key"
echo "     CINETPAY_SITE_ID=your-site-id"
echo "  5. Configure webhook URL in CinetPay dashboard:"
echo "     https://YOUR_PROJECT.supabase.co/functions/v1/cinetpay-webhook"
echo "  6. Deploy edge functions:"
echo "     supabase functions deploy cinetpay-checkout"
echo "     supabase functions deploy cinetpay-webhook"
echo ""

echo "--- Step 4: Sentry Configuration ---"
echo "  1. Go to https://sentry.io"
echo "  2. Create project (React)"
echo "  3. Set in Vercel: VITE_SENTRY_DSN=https://xxx@sentry.io/yyy"
echo ""

echo "--- Step 5: Email Configuration ---"
echo "  1. Go to https://resend.com"
echo "  2. Create API key"
echo "  3. Verify domain liasspilot.com"
echo "  4. Set in Supabase Edge Functions secrets:"
echo "     RESEND_API_KEY=re_..."
echo "     FROM_EMAIL=Liass'Pilot <noreply@liasspilot.com>"
echo ""

echo "--- Step 6: Deploy Edge Functions ---"
echo "  supabase functions deploy create-checkout"
echo "  supabase functions deploy stripe-webhook"
echo "  supabase functions deploy create-portal-session"
echo "  supabase functions deploy send-email"
echo ""

echo "--- Step 7: Security ---"
echo "  1. Regenerate Supabase anon key if previously exposed"
echo "  2. Verify all .env files are gitignored"
echo "  3. Ensure no secrets in git history (run: git log --all -p -- '*.env*')"
echo ""

echo "--- Step 8: Deploy ---"
echo "  git push origin main  # Triggers Vercel deployment"
echo ""

echo "============================================"
echo "  Setup guide complete!"
echo "============================================"
